#ifndef CONSTANTS_H
#define CONSTANTS_H

#define _WATERLEVEL_TRIG_PIN 23 // AMARILLO
#define _WATERLEVEL_ECHO_PIN 22 // AZUL
#define _DIGITALBALANCE_DOUT_PIN 26 // HX711 DATA OUT VERDE
#define _DIGITALBALANCE_CLK_PIN 27 // HX711 SCK IN AMARILLO

#define _CALIBRATIONFACTOR 399030 // Factor de calibración a 0.200 kg

#define _SECRET_SSID "rdajilaWifi"
#define _SECRET_PASS "1234izcbMj"

// Input JSON Dispenser Channel ThingSpeak
#define _SECRET_CH_ID 667670
#define _SECRET_WRITE_APIKEY "5M3W4B13NTT4L1S0"

#define _DELAY_SEND_DATA 25000

#define _MAX_DISTANCE 200

#endif
